### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by mstajdohar**

### CODE REVIEW

**Comment by mstajdohar** [comment]
We should probably write a [Sphinx extension](http://www.sphinx-doc.org/en/stable/extdev/index.html#dev-extensions) for generating the process catalog.

**Comment by mstajdohar** [comment]
@jkokosar, would you think about pipeline examples?

**Comment by mstajdohar** [comment]
@dblenkus, could you review this quickly? We would need to publish this docs together with the deploy.

**Comment by dblenkus** [comment]
Rebased and merged

**Pull request closed without merging**
