### PR TITLE
Update processes to support new input sanitization

### PR DESCRIPTION
**Pull request by kostko**
Requires genialis/resolwe#306

TODO
* [x] Fix remaining 19 tests.
* [x] Rebase as some processes have been moved to other repositories.

### CODE REVIEW

**Comment by kostko** [comment]
All tests fixed (with Resolwe from the linked PR), please review. I noticed several issues in general with Resolwe-bio, so this includes some other fixes as well (refactoring processes to not have overly long lines or doing strange things with bash). I didn't fix these issues in all the processes, I just went through those processes that needed changes due to new input sanitization code.

I hope that we have tests for all processes, as otherwise this may break badly or produce incorrect results. So all process authors, please review.

**Comment by kostko** [comment]
Yes, I've mostly refactored things where tests failed, but didn't look so much into processes where tests passed after the initial quote replacement. So there are more cases where at least the following should be done:
* Use arrays instead of string concatenation.
* Break long argument lists into multiple lines to improve readability.

**Comment by kostko** [comment]
Can I go ahead and merge this?

**Comment by mstajdohar** [comment]
Yes

**Pull request merged**
