### PR TITLE
Multi sample amplicon report

### PR DESCRIPTION
**Pull request by JureZmrzlikar**

### CODE REVIEW

**Comment by JureZmrzlikar** [comment]
Legacy data handling is fixed, as well as updated sorting of master file. Ready for review.

**Comment by mstajdohar** [comment]
@JureZmrzlikar Did you test this on a real data set locally (on your computer)?

**Comment by JureZmrzlikar** [comment]
Rebased and added changelog entries. Process was tested with real files locally, yes. This is not a breaking change but the configuartion should be modified:

- Upload template for multisample report (same file as in tests)
- Change name of archiver process to `amplicon-archive-multi-report`
- Harde two inputs to archiver process: id of logo genialis object and id of template object

**Comment by jkokosar** [comment]
Also, master file sorting has changed, so all master files need to be re-uploaded.

**Comment by jkokosar** [comment]
Please rebase

**Pull request merged**
