### PR TITLE
Split SRA process into two processes

### PR DESCRIPTION
**Pull request by dblenkus**

### CODE REVIEW

**Comment by mstajdohar** [comment]
> fastq-dump used in the processor relies on the external services (NCBI), with the smallest SRA files being >400 MB. We cannot write such a test without mocking NCBI services.

@dblenkus, you thoughts on this?

**Comment by dblenkus** [comment]
I agree that at the moment we can't write tests for these processes. If we want to cover such cases, we should discus how to do it (i.e. we can mock http response, inject our `fatsq-dump` command into docker which won't use internet,...). But all solutions are far from trivial.

**Comment by mstajdohar** [comment]
Rebase on to master.

**Comment by dblenkus** [comment]
Done.

**Pull request merged**
