### PR TITLE
Change ``samtools-bedcov`` process

### PR DESCRIPTION
**Pull request by marcellevstek**
* [x] Update CHANGELOG.rst for each commit separately:
  * Pay attention to write entries under the "Unreleased" section.
  * Mark all breaking changes as "**BACKWARD INCOMPATIBLE:**" and put them
    before non-breaking changes.
  * If a commit modifies a feature listed under "Unreleased" section,
    it might be sufficient to modify the existing CHANGELOG entry from previous
    commit(s).
* [x] Bump the process version:
  * **MAJOR version (first number)**: Backward incompatible changes (changes
    that break the api/interface). Examples: renaming the input/output, adding
    mandatory input, removing input/output...
  * **MINOR version (middle number)**: add functionality or changes in a
    backwards-compatible manner. Examples: add output field, add non-mandatory
    input parameter, use a different tool that produces same results...
  * **PATCH version (last number)**: changes/bug fixes that do not affect
    the api/interface. Examples: typo fix, change/add warning messages...
* [x] All inputs are used in process.
* [x] All output fields have a value assigned to them.

Rework output and labels in samtools-bedcov process. Coverage report is now compressed and labels shorted
to better render in frontend fields.

### CODE REVIEW

**Comment by marcellevstek** [comment]
Output file is now compressed and labels changed so they are better formatted on the frontend.

**Review by romunov — COMMENTED** [review]
PRs description could be improved, as well as the commit message. Perhaps mention that the report is now compressed. A commit message could be something along the lines of

> Rework output and labels in samtools-bedcov process
>
> Coverage report is now compressed and labels shorted
> to better render in frontend fields.

I also miss the changelog entry.

**Comment by jkokosar** [comment]
Squash the two commits together. @romunov Changelog entry is not needed for this commit, as the feature was not released yet.

**Comment by marcellevstek** [comment]
The function for calculating mean coverage was changed so it doesn't assume that there are only four initial columns. This is something that was OK at the start, but I wanted to make the code prettier and thus ran into problems.

**Review by jkokosar — APPROVED** [review]

**Pull request merged**
