### PR TITLE
Fixed genus species names

### PR DESCRIPTION
**Pull request by mzganec**
Fixed genus species names to be consistent in spelling and capitalization, [https://github.com/genialis/bug-reports/issues/25](https://github.com/genialis/bug-reports/issues/25).

### CODE REVIEW

**Comment by dblenkus** [comment]
Be aware that this will raise validation error on save for all existing samples with this descriptor schema.

**Comment by mzganec** [comment]
@dblenkus Note that only the labels were changed and the corresponding values remained the same. I presume that only the values are important in validation and not the labels.

**Comment by jkokosar** [comment]
Also, this schemas were not attached to any samples. They are used only to configure/trigger primary analysis workflows.

**Comment by dblenkus** [comment]
> @dblenkus Note that only the labels were changed and the corresponding values remained the same. I presume that only the values are important in validation and not the labels.

Ok, I've missed this :)

**Comment by mstajdohar** [comment]
Rebase to master, please.

**Pull request merged**
