### PR TITLE
Add GOTEA to resolwebio/rnaseq docker image

### PR DESCRIPTION
**Pull request by JenkoB**
@tjanez when building docker I got Error messages: ```Failed building wheel for slumber```, the same for `wrapt`, `dexseq-prepare-annotation2`, `pyyaml`.

Jan will correct the warning messages regarding preprocessor and processor.
@dblenkus please check and @JureZmrzlikar please tag the process when it will be approved

### CODE REVIEW

**Comment by mzganec** [comment]
> when building docker I got Error messages: Failed building wheel for slumber, the same for wrapt, dexseq-prepare-annotation2, pyyaml.

@jvrakor Didn't we fix this [here](https://github.com/genialis/resolwe-bio/blob/master/resolwe_bio/docker_images/rnaseq/packages-debian-buildreq.txt#L3) by installing `python3-wheel`?

**Comment by jvrakor** [comment]
@mzganec We did. Previous Docker image was built without any errors: https://hub.docker.com/r/resolwebio/rnaseq/builds/bm58cpqglqbzcscj6daoukh/.

**Comment by mzganec** [comment]
Yes, the SHA256 mismatch is expected and occurs also on DockerHub. Thanks for testing! @JenkoB Please correct the hash. @tjanez Shall we put manually installed packages to our data server to prevent this from happening in the future?

**Comment by JenkoB** [comment]
Thanks @mzganec and @jvrakor. I will change the hash for sratoolkit.

**Comment by jkokosar** [comment]
@JenkoB sra-toolkit is removed from `rnaseq` image [here](https://github.com/genialis/resolwe-bio/pull/508) since the sra import process now uses `utils` image.

**Pull request merged**
