### PR TITLE
Fix feature query to not hit the clause limit

### LINKED ISSUE #181: Feature query fails for many genes
Issue moved from https://github.com/genialis/resolwe-bio-py/issues/78

To reproduce, run:

```py
import resdk
res = resdk.Resolwe(url='https://qa.genialis.com')

res.feature.filter(source="NCBI", query=range(300)) # works
res.feature.filter(source="NCBI", query=range(400)) # fails
```

---

Elastic search traceback:
```
Traceback:

File "/srv/genialis/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/srv/genialis/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/genialis/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/srv/genialis/venv/lib/python2.7/site-packages/rest_framework/viewsets.py" in view
  83.             return self.dispatch(request, *args, **kwargs)

File "/srv/genialis/venv/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  477.             response = self.handle_exception(exc)

File "/srv/genialis/venv/lib/python2.7/site-packages/rest_framework/views.py" in handle_exception
  437.             self.raise_uncaught_exception(exc)

File "/srv/genialis/venv/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  474.             response = handler(request, *args, **kwargs)

File "/srv/genialis/venv/lib/python2.7/site-packages/resolwe/elastic/viewsets.py" in list_with_post
  158.         return self.paginate_response(search)

File "/srv/genialis/venv/lib/python2.7/site-packages/resolwe/elastic/viewsets.py" in paginate_response
  120.         return Response(serializer.data)

File "/srv/genialis/venv/lib/python2.7/site-packages/rest_framework/serializers.py" in data
  725.         ret = super(ListSerializer, self).data

File "/srv/genialis/venv/lib/python2.7/site-packages/rest_framework/serializers.py" in data
  262.                 self._data = self.to_representation(self.instance)

File "/srv/genialis/venv/lib/python2.7/site-packages/rest_framework/serializers.py" in to_representation
  643.             self.child.to_representation(item) for item in iterable

File "/srv/genialis/venv/lib/python2.7/site-packages/elasticsearch_dsl/search.py" in __iter__
  233.         return iter(self.execute())

File "/srv/genialis/venv/lib/python2.7/site-packages/elasticsearch_dsl/search.py" in execute
  627.                     **self._params

File "/srv/genialis/venv/lib/python2.7/site-packages/elasticsearch/client/utils.py" in _wrapped
  69.             return func(*args, params=params, **kwargs)

File "/srv/genialis/venv/lib/python2.7/site-packages/elasticsearch/client/__init__.py" in search
  539.             doc_type, '_search'), params=params, body=body)

File "/srv/genialis/venv/lib/python2.7/site-packages/elasticsearch/transport.py" in perform_request
  327.                 status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)

File "/srv/genialis/venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py" in perform_request
  109.             self._raise_error(response.status, raw_data)

File "/srv/genialis/venv/lib/python2.7/site-packages/elasticsearch/connection/base.py" in _raise_error
  113.         raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

Exception Type: TransportError at /api/kb/feature/search
Exception Value: TransportError(500, u'search_phase_execution_exception', u'maxClauseCount is set to 1024')
```

### PR DESCRIPTION
**Pull request by kostko**
Should fix #181

### CODE REVIEW

**Comment by kostko** [comment]
@jkokosar can you test this and see if this fixes the problem you are having (#181)?

**Comment by mstajdohar** [comment]
Elasticsearch connection timeout in a Python 3.4 test. Otherwise the code is ok.

**Comment by jkokosar** [comment]
Tested, looks ok. However, other issue was discovered during testing: https://github.com/genialis/resolwe/issues/195

**Comment by kostko** [comment]
Ok, I'll look into it.

**Pull request merged**
