### PR TITLE
Add knowledge base app

### PR DESCRIPTION
**Pull request by kostko**
* [x] Tests.
* [x] REST endpoint for `Feature` (admin-only access).
* [x] Query by list of identifiers.

### CODE REVIEW

**Comment by dblenkus** [comment]
Do you need any haystack related setting in resolwe-bio's test project?

**Comment by kostko** [comment]
Yes, I will add them when I start adding tests.

**Comment by mstajdohar** [comment]
The coverage check fails because we do not test the `admin.py`. Should we test it? What do we do in this case, accept anyway?

**Comment by kostko** [comment]
How can we test `admin.py`?

**Comment by mstajdohar** [comment]
I don't know. This is why I asked if we should test it... :)

**Pull request merged**
