### PR TITLE
Refactor for updated Resolwe

### PR DESCRIPTION
**Pull request by kostko**
This requires genialis/resolwe#138.

### CODE REVIEW

**Comment by dblenkus** [comment]
@mstajdohar, @tjanez, @jkokosar: Is there a reason to use `|default(src.file)` in first argument of `re-import` function? I.e.: 

    re-import "{{ src2.file_temp|default(src2.file) }}" "{{ src2.file }}" "bai" "bai" 0.3 extract

If not, we can remove it now when all processes are being refactored

**Comment by dblenkus** [comment]
@kostko version of all changed processes must be increased

**Comment by kostko** [comment]
Which version atom should be changed (eg. major/minor version) or is this arbitrary as long as the version is increased?

**Comment by mstajdohar** [comment]
Arbitrary as long as the version is increased.

**Comment by mstajdohar** [comment]
We can remove the `|default(src.file)` when moving uploaded files. All uploaded files have the `.file_temp` field. Should we make the `. file_temp` field required on inputs?

**Comment by kostko** [comment]
For future reference, to bump process versions in a single line of bash:
```bash
find -name "*.yml" -exec sed -i -r 's/(\s+)version: ([0-9]+)\.([0-9]+)\.([0-9]+)/echo "\1version: \2.\3.$((\4 + 1))"/ge' {} \;
```

**Comment by mstajdohar** [comment]
> For future reference, to bump process versions in a single line of bash...

That is dangerous so if you use it in the future, do it with thought and caution.

**Comment by kostko** [comment]
> This is dangerous so if you use it in the future, do it with thought and caution.

Yes, you just have to take care to only match processors that were actually updated (and not also descriptor schemas, etc.) and review the changes before committing them.

**Comment by kostko** [comment]
Rebased on latest master, please review.

**Pull request merged**
