### PR TITLE
 Use the new resolwebio/chipseq:1.1.0 docker image in macs14 process 

### PR DESCRIPTION
**Pull request by jvrakor**
@jkokosar @mstajdohar 

Built on top of https://github.com/genialis/resolwe-bio/pull/413

### CODE REVIEW

**Comment by jkokosar** [comment]
@jvrakor you need to separate the last commit into its own PR

**Comment by jvrakor** [comment]
@jkokosar when #413 will be merged this will become one commit. I just prepared it in advance.

**Comment by mstajdohar** [comment]
Rebase

**Comment by mstajdohar** [comment]
Make the commit message shorter, for instance "Run macs14 in resolwebio/chipseq:1.1.0 docker image". Then you can add a paragraph to the commit message explaining what is new about macs14 in this image.

**Pull request merged**
