### PR TITLE
Use resolwebio/rnaseq Docker image in STAR index

### PR DESCRIPTION
**Pull request by JenkoB**
## Checklist

* [x] Update CHANGELOG.rst for each commit separately:
  * Pay attention to write entries under the "Unreleased" section.
  * Mark all breaking changes as "**BACKWARD INCOMPATIBLE:**" and put them
    before non-breaking changes.
  * If a commit modifies a feature listed under "Unreleased" section,
    it might be sufficient to modify the existing CHANGELOG entry from previous
    commit(s).
* [x] Bump the process version:
  * **MAJOR version (first number)**: Backward incompatible changes (changes
    that break the api/interface). Examples: renaming the input/output, adding
    mandatory input, removing input/output...
  * **MINOR version (middle number)**: add functionality or changes in a
    backwards-compatible manner. Examples: add output field, add non-mandatory
    input parameter, use a different tool that produces same results...
  * **PATCH version (last number)**: changes/bug fixes that do not affect
    the api/interface. Examples: typo fix, change/add warning messages...
* [ ] All inputs are used in process.
* [ ] All output fields have their ``re-save`` calls.

### CODE REVIEW

**Comment by JenkoB** [comment]
@JureZmrzlikar @mzganec

**Comment by JenkoB** [comment]
As suggested I have raised minor version of process. 
I have checked sizes of all output files, when running tests on star index and they remained the same. I also went through STAR changelog.

@jkokosar @mzganec @JureZmrzlikar

**Comment by JureZmrzlikar** [comment]
> I have checked sizes of all output files, when running tests on star index and they remained the same

Can you also update tests to check for sizes?

**Comment by mstajdohar** [comment]
@JenkoB Thanks! Please do as Jure suggests (update the tests to check for sizes), then this is good to be merged.

**Comment by JenkoB** [comment]
I am waiting for this PR: https://github.com/genialis/resolwe/pull/482 to be merged. Then I can write these tests.

**Comment by mzganec** [comment]
I'll move https://github.com/genialis/resolwe/pull/482 forward towards the end of this week, just after clustering.

**Comment by mstajdohar** [comment]
Hmm, then I suggest we merge this change so we can start testing it on QA.

**Comment by mstajdohar** [comment]
Please rebase

**Comment by JenkoB** [comment]
I have added tests as Jure suggested and rebased. We can additionally improve tests later.

**Pull request merged**
